import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar"
import Footer from "./components/layout/Footer";
import { ThemeProvider } from "./contexts/ThemeContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KITTINAN | RESUME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="dark" lang="en">
      <link
  rel="icon"
  href="/image/icontitle/icons8.png"
  type="image/png"
  sizes="32x32"
/>
      <body className={inter.className}  >
      <ThemeProvider>
      <div className="min-w-full min-h-full">
      <Navbar/>
      {children}
      <Footer/>
      </div>
      </ThemeProvider>
     </body>
    </html>
  );
}
